[package]
name = "dog3"
version = "0.1.0"
edition = "2021"
authors = ["Henrique Colini <henriquecolini@gmail.com>"]

[dependencies]
clap = { version = "4.3.3", features = ["derive"] }
minreq = { version = "2.11.0", features = ["https"] }
pest = "2.0"
pest_derive = "2.0"

[[bin]]
name = "dog3"
